# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Realm实战' do

   use_frameworks!
   pod 'Realm', '~> 2.1.2'    

   target 'Realm实战Tests' do
    inherit! :search_paths

  end

end
